version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: start_pack_boilerplate_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: start_pack_boilerplate_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - start_pack_boilerplate_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: start_pack_boilerplate_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: Password!
    ports:
      - "8080:80"
    networks:
      - start_pack_boilerplate_network

networks:
  start_pack_boilerplate_network:

volumes:
  mysql_data:
